### ISSUE TITLE
Create Denmark

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#15]
Use public data from Denmark and:

- [x] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [ ] Upload to Source Cooperative
- [ ] Get STAC, STAC Browser and PMTiles
- [ ] Make nice readme for source cooperative.

**Comment by m-mohr** [comment]
Any updates on this @DanielNwaeze ?

**Comment by DanielNwaeze** [comment]
I was assigned Slovenia instead since then

**Comment by m-mohr** [comment]
Denmark is done, isn't it? @ivorbosloper

**Comment by ivorbosloper** [comment]
@m-mohr yes, it's done. Someone could close the issue :)
