### ISSUE TITLE
Create Finland

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#16]
Use public data from Finland and:

- [x] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [ ] Make nice readme for source cooperative.

**Comment by ivorbosloper** [comment]
Published https://beta.source.coop/repositories/fiboa/finland/
