### ISSUE TITLE
Create Netherlands

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#17]
Use public data from the Netherlands and:

- [x] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [x] Make nice readme for source cooperative.

**Comment by m-mohr** [comment]
@ivorbosloper is working on this

**Comment by ivorbosloper** [comment]
@m-mohr I tried to follow-up on the howto and published the Field Blocks at https://beta.source.coop/repositories/fiboa/nl-ref/ . Are there any next steps?

The minimum string length of repo-names is 3, so "nl" is not an option. Ideally we define a consisten naming strategy (we also have https://beta.source.coop/repositories/fiboa/austria/ ).

**Comment by m-mohr** [comment]
Awesome! Just add the link to the collection here:
https://github.com/fiboa/fiboa.github.io/blob/main/stac/catalog.json
Afterwards, this issue can be closed, I think.

The naming is indeed not very consistent. I'm not sure we need one for the repository names. I guess I also used austria instead of at because of the 3 char minimum.

**Comment by ivorbosloper** [comment]
Also done for https://beta.source.coop/repositories/fiboa/nl-crop/ . Created https://github.com/fiboa/fiboa.github.io/pull/2

**Comment by m-mohr** [comment]
Thanks, merged. 

The NL datasets will now appear shortly on https://radiantearth.github.io/stac-browser/#/external/fiboa.org/stac/catalog.json?.language=en and tomorrow on https://github.com/fiboa/data
