### ISSUE TITLE
Create Sweden

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#19]
Use public data from Sweden and:

- [ ] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [ ] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [ ] Run the conversion and validate
- [ ] Upload to Source Cooperative
- [ ] Get STAC, STAC Browser and PMTiles
- [ ] Make nice readme for source cooperative.

**Comment by cholmes** [comment]
Dataset at https://www.geodata.se/geodataportalen/srv/swe/catalog.search;jsessionid=6C2D281619D69AC2356E1BD4C1923A3A#/metadata/df439ba5-014e-44ec-86cb-ddb9e5ba306c

**Comment by m-mohr** [comment]
Sweden is done, isn't it @ivorbosloper ?

**Comment by ivorbosloper** [comment]
Allmost done: 

https://github.com/fiboa/cli/pull/96 
https://github.com/fiboa/data-survey/pull/23

**Comment by ivorbosloper** [comment]
Yes, it's published & live. If not done, file a bug :)

**Comment by ivorbosloper** [comment]
Is there a way to close this issue @cholmes @m-mohr ? I've moved it to Done

**Comment by cholmes** [comment]
> Is there a way to close this issue @cholmes @m-mohr ? I've moved it to Done

Just tried to upgrade your access - you may need to click yes on an invite.
