### ISSUE TITLE
Release ASU Field Boundary AI Dataset

### ISSUE THREAD

**Issue by PowerChell** [fiboa/data#2]
- [ ] Produce first version of the dataset 
- [ ] Using the AI ecosystem extension and implementing Fiboa
- [ ] Convert/make sure it’s valid Fiboa, in GeoParquet & GeoJSON @m-mohr 
- [ ] On Source Cooperative under ASU org account (@PowerChell to help ASU set up org account) 
- [ ] Available in GeoJSON and GeoParquet, both validating

**Comment by cholmes** [comment]
Marking this one as done, as a first version is certainly out.
