### ISSUE TITLE
Create Luxembourg

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#24]
Use public data from Luxemberg and:

- [x] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [x] Make nice readme for source cooperative.

Instructions available at https://github.com/fiboa/data/blob/main/HOWTO.md

**Comment by cholmes** [comment]
Data at https://data.public.lu/en/datasets/referentiel-des-parcelles-flik/#resources

CC0

<img width="994" alt="Screenshot 2024-05-24 at 11 50 08 AM" src="https://github.com/fiboa/data/assets/407017/a6550ed1-2ec6-4008-aa7e-798827fbe00c">

This also has all the years available, so would be a good one to explore time series with. Make one fiboa file per year, and then also a 'merge' fiboa that combines them all.

**Comment by ivorbosloper** [comment]
Can we close this one @cholmes ?

**Comment by cholmes** [comment]
Sure! Do you not have permissions to close yet?
