### ISSUE TITLE
Create Cambodia

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#26]
Use public data from Cambodia and:

- [ ] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [x] Make nice readme for source cooperative.

Instructions available at https://github.com/fiboa/data/blob/main/HOWTO.md

**Comment by cholmes** [comment]
Data is in https://phys-techsciences.datastations.nl/dataset.xhtml?persistentId=doi:10.17026/dans-xy6-ngg6

It's a lot of individual geopackages - hopefully we can get a process to pull them and combine them, or else we could just do a one time conversion and put the result on source (and build the converters from there - we'll likely want to re-run converters as fiboa evolves).

**Comment by m-mohr** [comment]
I thought I could just download by iterating through the files (i.e. download 0_... then 1_... etc, but the platform is generating IDs that don't seem to have a consistent structure, so you'd need to individually copy all URLs into the template.

The CLI has support to handle multiple input files now and merge into a single file, but copy/pasting all URLs manually will be annoying.

**Comment by cholmes** [comment]
Started this at https://github.com/fiboa/cli/pull/83

And yeah, I'll just copy the id's manually...

**Comment by m-mohr** [comment]
Done: https://beta.source.coop/repositories/fiboa/ai4sf/description/
