### ISSUE TITLE
Determine list of datasets to convert to Fiboa

### ISSUE THREAD

**Issue by PowerChell** [fiboa/data#3]
Covert X (3? 6?) datasets (source ASU ones, other gov ones, samples from commercial providers) to Fiboa to go along side the ASU , put up as good examples on Source Cooperative either under the fiboa organization or under data provider organization (e.g. ASU).

Potenential Options:
- Eurocrops 
- ...
- ...

**Comment by m-mohr** [comment]
I'll try to convert:
- [ ] DE-NRW
- [ ] DE-BB
- [ ] DE-SH

**Comment by m-mohr** [comment]
Maybe UK: https://environment.data.gov.uk/rpa/api-doc/
Was mentioned in a recent email.

**Comment by cholmes** [comment]
I think France from Eurocrops would also be good. It's the largest eurocrops dataset (2.6 gig), so would be a good set of additional fields. I feel like it's also often used for training data, so it's I think one of the higher quality data sets.

**Comment by m-mohr** [comment]
Should also be a good test for the CLI... I'll open a separate issue for it and assign me for now, but if anyone else wants to do it after watching the recent tutorial, please go ahead!

**Comment by cholmes** [comment]
I think we can close this one, as we certainly got a great set for the initial release - thanks @m-mohr! I think there's more to add, but we can just do each new potential one as a new issue.
