### ISSUE TITLE
Create Slovenia (from eurocrops)

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#31]
Use public data from Eurocrops from Slovenia and:

- [ ] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [x] Make nice readme for source cooperative.

Can download at https://zenodo.org/records/8229128/files/SI_2021.zip?download=1 and additional information at https://github.com/maja601/EuroCrops/wiki/Slovenia

Eventually we should also make a converter & dataset that pulls directly from the Slovenia government.

**Comment by m-mohr** [comment]
I don't see it on Source yet, although the checkmarks are ticked here?

**Comment by DanielNwaeze** [comment]
It's available at: https://beta.source.coop/repositories/fiboa/slovenia-ec/description/
It's presently unlisted as I was awaiting for your PR since I'll have to make the minor changes on the PR to its metadata on Source. Do you have access to the Fiboa organisation? You should see it
