### ISSUE TITLE
Create Vietnam from AI4SmallFarms dataset

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#32]
Use public data from [AI4SmallFarms](https://phys-techsciences.datastations.nl/dataset.xhtml?persistentId=doi:10.17026/dans-xy6-ngg6)

- [x] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [x] Make nice readme for source cooperative.

Can download at https://phys-techsciences.datastations.nl/dataset.xhtml?persistentId=doi:10.17026/dans-xy6-ngg6 

It will take some processing to combine all the geopackages for vietnam into one data set. 

License is CC-BY-4.0

**Comment by m-mohr** [comment]
Done
