### ISSUE TITLE
Create Portugal

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#35]
Use public data from Portugal and:

- [x] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [x] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [x] Run the conversion and validate
- [x] Upload to Source Cooperative
- [x] Get STAC, STAC Browser and PMTiles
- [x] Make nice readme for source cooperative.

Instructions available at https://github.com/fiboa/data/blob/main/HOWTO.md

Data available at https://www.ifap.pt/isip/ows/ - looks like it has it for every year. Ideally make one fiboa file per year, and then when we figure out time stamps extension we can make one big merged one.

It says 'open data', but would be good to get more clarity on the license.

**Comment by m-mohr** [comment]
Done: https://beta.source.coop/repositories/fiboa/portugal/description/
