### ISSUE TITLE
Africa (mid/south) from Lacuna

### ISSUE THREAD

**Issue by m-mohr** [fiboa/data#41]
Crop field boundary labels for Africa, [Funded by Lacuna](https://lacunafund.org/five-new-machine-learning-datasets-in-agriculture-health-and-language-domains/), on [Zenodo](https://zenodo.org/records/11060871), [GH](https://github.com/agroimpacts/lacunalabels), [AWS](https://registry.opendata.aws/africa-field-boundary-labels/)
[PMTiles preview of coverage and extent](https://pmtiles.io/?url=https%3A%2F%2Fpub-6ea2575104d44fbda52a88736af161e7.r2.dev%2Flacuna_fields_data.pmtiles#map=3.71/-6.41/15.05)

- [ ] Add it to the [data survey](https://github.com/fiboa/data-survey) (optional)
- [ ] Make the [template](https://github.com/fiboa/cli/blob/main/fiboa_cli/datasets/template.py) for the CLI (and contribute it back)
- [ ] Run the conversion and validate
- [ ] Upload to Source Cooperative
- [ ] Get STAC, STAC Browser and PMTiles
- [ ] Make nice readme for source cooperative.

**Comment by kovaca** [comment]
Sign me up, chief

**Comment by ivorbosloper** [comment]
I think it's a duplicate from https://github.com/fiboa/data/issues/44 . Just implemented the converter..

**Comment by m-mohr** [comment]
I guess #44 is a duplicate of this, but nvm.
