### ISSUE TITLE
Enhance NRW Germany dataset to be an examplar cloud native geo dataset.

### ISSUE THREAD

**Issue by cholmes** [fiboa/data#5]
There are a few things we could do to follow-on from #1 

- [x] ~Add GeoJSON version~ skip for now
- [x] PMTiles version, ideally with some nice styling, that can be seen directly in the source viewer
- [x] STAC metadata, just collection level, linking to the constituent files.
- [x] Link to STAC Browser
- [x] ~Links to any tutorials / tools that work with it.~

Moved "Registered on STAC index" to #10 
Moved tutorial to https://github.com/fiboa/communications/issues/1

**Comment by m-mohr** [comment]
Moved to https://github.com/fiboa/communications/issues/1
